const PROJECTS = [
    {
      id: 'gravity',
      title: 'Gravity',
      desc: 'Strumento per creare simulazioni fisiche interattive con immagini personalizzate. Supporta gravità, attrito e rimbalzi configurabili.',
      tags: ['p5.js'],
      href: 'https://leowl-m.github.io/training-gravity/',
      addedAt: '2026-04-04T21:30:00Z',
      status: 'stable',
      version: '1.2',
    },
    {
      id: 'flowerpixel',
      title: 'Flower Pixel',
      desc: 'Pattern da immagine con jitter, contrasto e palette. Ottimo per effetti glitch e dithering artistico.',
      tags: ['p5.js'],
      href: 'https://leowl-m.github.io/training-flowerpixel/',
      repoHref: 'https://github.com/leowl-M/training-flowerpixel',
      addedAt: '2025-07-02T08:00:00Z',
      status: 'stable',
      version: '1.0',
    },
    {
      id: 'officinaditheris',
      title: 'Officina Ditheris',
      desc: 'Strumento avanzato per creativi che trasforma le immagini digitali usando tecniche di dithering classiche e sperimentali.',
      tags: ['Figma'],
      href: 'https://www.figma.com/community/plugin/1556657188945716249/officina-ditheris',
      addedAt: '2026-04-04T21:30:00Z',
      status: 'online',
      version: '1.4',
    },
    {
      id: 'modulink',
      title: 'Modulink',
      desc: "Strumento per Figma che automatizza l'organizzazione dei link tra frame e componenti nel tuo progetto.",
      tags: ['Figma'],
      href: 'https://www.figma.com/community/plugin/1556657188945716249/officina-ditheris',
      addedAt: '2026-04-04T21:30:00Z',
      status: 'online',
      version: '1.1',
    },
    {
      id: 'collage',
      title: 'Collage Dinamico',
      desc: 'Strumento p5.js per creare collage dinamici sovrapponendo forme e immagini con blend modes avanzati.',
      tags: ['p5.js'],
      href: 'https://leowl-M.github.io/training-collage/',
      addedAt: '2025-06-20T10:00:00Z',
      status: 'stable',
      version: '1.0',
    },
    {
      id: 'blobtracking',
      title: 'Blob Tracking',
      desc: 'Rilevamento e tracciamento di blob in tempo reale usando la webcam e algoritmi di computer vision.',
      tags: ['p5.js'],
      href: 'https://leowl-M.github.io/training-blobtracking/',
      addedAt: '2025-05-11T09:00:00Z',
      status: 'stable',
      version: '1.0',
    },
    {
      id: 'dithering',
      title: 'Dithering & Posterize',
      desc: 'Esplorazione di algoritmi di dithering (Floyd-Steinberg, ecc.) e posterizzazione su immagini.',
      tags: ['p5.js'],
      href: 'https://leowl-M.github.io/training-dithering/',
      addedAt: '2025-04-02T08:00:00Z',
      status: 'stable',
      version: '1.0',
    },
    {
      id: 'articleimage',
      title: 'Article Image',
      desc: 'Generatore di immagini per articoli di blog. Supporta layout multipli, tipografia e palette personalizzabili.',
      tags: ['p5.js'],
      href: 'https://leowl-m.github.io/article-image/',
      addedAt: '2025-04-02T08:00:00Z',
      status: 'wip',
      version: '1.0',
    },
  ];